[project]
name = "torrent-bot"
version = "0.1.0"
description = "Torrent bot for Telegram"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aiogram>=3.22.0",
    "pydantic-settings>=2.12.0",
    "torrent-parser>=0.4.1",
]
